version: 2
jobs:
  build:
    machine: true
    working_directory: ~/go/src/github.com/denismakogon/snyk-filter
    environment: # apparently expansion doesn't work here yet: https://discuss.circleci.com/t/environment-variable-expansion-in-working-directory/11322
      - GO111MODULE=on
      - GOFLAGS=-mod=vendor
      - GOPATH=/home/circleci/go
      - GOVERSION=1.12.3
      - OS=linux
      - ARCH=amd64
    steps:
      - checkout
      - run: make release
