version: 2
jobs:
  build:
    machine: true
    working_directory: ~/go/src/github.com/denismakogon/snyk-filter
    environment: # apparently expansion doesn't work here yet: https://discuss.circleci.com/t/environment-variable-expansion-in-working-directory/11322
      - GO111MODULE=on
      - GOFLAGS=-mod=vendor
      - GOPATH=/home/circleci/go
      - GOVERSION=1.12.3
      - OS=linux
      - ARCH=amd64
    steps:
      - checkout
      - deploy:
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" && -z "${CIRCLE_PR_REPONAME}" ]]; then
              printenv DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              git config --global user.email "ci@fnproject.com"
              git config --global user.name "CI"
              git branch --set-upstream-to=origin/${CIRCLE_BRANCH} ${CIRCLE_BRANCH}
              ./release.sh
            fi
